# Generated by Django 4.2.7 on 2023-11-26 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=50)),
                ('exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('minLevel', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=200)),
                ('gold', models.IntegerField(default=200)),
                ('time', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStart', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.quest')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.party'),
        ),
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.profession'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.skill'),
        ),
    ]
